const { PrismaClient } = require('@prisma/client')
const p = new PrismaClient()
p.user.findFirst({ select: { email: true, role: true, tenantId: true } })
  .then((u) => console.log(JSON.stringify(u, null, 2)))
  .finally(() => p.$disconnect())
