import { Injectable, NotFoundException, Logger } from '@nestjs/common'
import { PrismaService } from '../../common/prisma/prisma.service'
import { AIService } from '../../ai/ai.service'
import * as fs from 'fs'
import * as path from 'path'
import * as crypto from 'crypto'

// ── HTML Templates ────────────────────────────────────────────────

function wrapHTML(title: string, body: string, company = 'Your Company'): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e; background: #fff; font-size: 13px; line-height: 1.6; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
    .company-name { font-size: 22px; font-weight: 700; color: #2563eb; }
    .doc-title { font-size: 18px; font-weight: 600; color: #1e293b; margin-top: 4px; }
    .doc-meta { text-align: right; font-size: 11px; color: #64748b; }
    h2 { font-size: 14px; font-weight: 600; color: #2563eb; text-transform: uppercase; letter-spacing: 0.05em; margin: 24px 0 10px; border-left: 3px solid #2563eb; padding-left: 8px; }
    table { width: 100%; border-collapse: collapse; margin: 10px 0; }
    th { background: #2563eb; color: white; padding: 8px 12px; text-align: left; font-size: 11px; text-transform: uppercase; }
    td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
    tr:nth-child(even) td { background: #f8fafc; }
    .total-row td { font-weight: 700; background: #eff6ff; border-top: 2px solid #2563eb; }
    .badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 11px; font-weight: 600; }
    .badge-blue { background: #dbeafe; color: #1d4ed8; }
    .badge-green { background: #dcfce7; color: #15803d; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 12px 0; }
    .info-block { padding: 12px; background: #f8fafc; border-radius: 8px; }
    .info-label { font-size: 10px; text-transform: uppercase; color: #94a3b8; font-weight: 600; margin-bottom: 4px; }
    .info-value { font-size: 13px; color: #1e293b; }
    p { margin: 6px 0; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="company-name">${company}</div>
      <div class="doc-title">${title}</div>
    </div>
    <div class="doc-meta">
      <div>Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
      <div>Doc #: ${crypto.randomBytes(3).toString('hex').toUpperCase()}</div>
    </div>
  </div>
  ${body}
  <div class="footer">Generated by AI Workforce OS · ${company}</div>
</body>
</html>`
}

const TEMPLATES: Record<string, (data: any, company: string) => string> = {
  estimate: (data, company) => wrapHTML('ESTIMATE / PROPOSAL', `
    <div class="info-grid">
      <div class="info-block"><div class="info-label">Customer</div><div class="info-value">${data.customerName ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Property Address</div><div class="info-value">${data.address ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Phone</div><div class="info-value">${data.phone ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Email</div><div class="info-value">${data.email ?? 'N/A'}</div></div>
    </div>
    <h2>Scope of Work</h2>
    <p>${data.scopeOfWork ?? 'To be determined during site inspection.'}</p>
    <h2>Line Items</h2>
    <table>
      <tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>
      ${(data.lineItems ?? []).map((li: any) => `<tr><td>${li.description}</td><td>${li.qty ?? 1}</td><td>$${Number(li.unitPrice ?? 0).toFixed(2)}</td><td>$${(Number(li.qty ?? 1) * Number(li.unitPrice ?? 0)).toFixed(2)}</td></tr>`).join('')}
      <tr class="total-row"><td colspan="3">TOTAL</td><td>$${(data.total ?? (data.lineItems ?? []).reduce((s: number, i: any) => s + (i.qty ?? 1) * (i.unitPrice ?? 0), 0)).toFixed(2)}</td></tr>
    </table>
    <h2>Notes</h2>
    <p>${data.notes ?? 'This estimate is valid for 30 days from the date above.'}</p>
  `, company),

  inspection: (data, company) => wrapHTML('INSPECTION REPORT', `
    <div class="info-grid">
      <div class="info-block"><div class="info-label">Property Address</div><div class="info-value">${data.address ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Customer</div><div class="info-value">${data.customerName ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Inspector</div><div class="info-value">${data.inspector ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Date Inspected</div><div class="info-value">${data.inspectionDate ?? new Date().toLocaleDateString()}</div></div>
    </div>
    <h2>Overall Condition</h2>
    <p><span class="badge badge-blue">${data.overallCondition ?? 'Requires Assessment'}</span></p>
    <p style="margin-top:8px">${data.summary ?? ''}</p>
    <h2>Findings</h2>
    <table>
      <tr><th>Area</th><th>Condition</th><th>Severity</th><th>Notes</th></tr>
      ${(data.findings ?? []).map((f: any) => `<tr><td>${f.area}</td><td>${f.condition}</td><td><span class="badge ${f.severity === 'High' ? 'badge-blue' : 'badge-green'}">${f.severity}</span></td><td>${f.notes ?? ''}</td></tr>`).join('')}
    </table>
    <h2>Recommended Actions</h2>
    <p>${data.recommendations ?? 'Full replacement recommended within 6 months.'}</p>
    <h2>Photos / Evidence</h2>
    <p>${data.photos ?? 'Photos taken and available upon request.'}</p>
  `, company),

  sow: (data, company) => wrapHTML('STATEMENT OF WORK', `
    <div class="info-grid">
      <div class="info-block"><div class="info-label">Project</div><div class="info-value">${data.projectTitle ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Customer</div><div class="info-value">${data.customerName ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Start Date</div><div class="info-value">${data.startDate ?? 'TBD'}</div></div>
      <div class="info-block"><div class="info-label">Completion</div><div class="info-value">${data.endDate ?? 'TBD'}</div></div>
    </div>
    <h2>Project Overview</h2>
    <p>${data.overview ?? ''}</p>
    <h2>Deliverables</h2>
    ${(data.deliverables ?? []).map((d: string) => `<p>• ${d}</p>`).join('')}
    <h2>Materials</h2>
    <table>
      <tr><th>Material</th><th>Quantity</th><th>Supplier</th></tr>
      ${(data.materials ?? []).map((m: any) => `<tr><td>${m.name}</td><td>${m.quantity} ${m.unit ?? ''}</td><td>${m.supplier ?? 'TBD'}</td></tr>`).join('')}
    </table>
    <h2>Terms & Conditions</h2>
    <p>${data.terms ?? 'Payment due upon project completion. Warranty: 1 year on workmanship.'}</p>
  `, company),

  invoice: (data, company) => wrapHTML('INVOICE', `
    <div class="info-grid">
      <div class="info-block"><div class="info-label">Bill To</div><div class="info-value">${data.customerName ?? 'N/A'}<br>${data.address ?? ''}</div></div>
      <div class="info-block"><div class="info-label">Invoice Details</div><div class="info-value">Due: ${data.dueDate ?? '30 days'}<br>Status: <span class="badge badge-blue">${data.status ?? 'Unpaid'}</span></div></div>
    </div>
    <h2>Services Rendered</h2>
    <table>
      <tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>
      ${(data.lineItems ?? []).map((li: any) => `<tr><td>${li.description}</td><td>${li.qty ?? 1}</td><td>$${Number(li.rate ?? li.unitPrice ?? 0).toFixed(2)}</td><td>$${(Number(li.qty ?? 1) * Number(li.rate ?? li.unitPrice ?? 0)).toFixed(2)}</td></tr>`).join('')}
      <tr class="total-row"><td colspan="3">TOTAL DUE</td><td>$${(data.total ?? 0).toFixed(2)}</td></tr>
    </table>
    <h2>Payment Instructions</h2>
    <p>${data.paymentInstructions ?? 'Please make payment via bank transfer or check. Include invoice number as reference.'}</p>
  `, company),
}

@Injectable()
export class DocumentsService {
  private readonly logger = new Logger(DocumentsService.name)
  private readonly outputDir = path.join(process.cwd(), 'generated-docs')

  constructor(
    private readonly prisma: PrismaService,
    private readonly ai: AIService,
  ) {
    if (!fs.existsSync(this.outputDir)) fs.mkdirSync(this.outputDir, { recursive: true })
  }

  findAll(tenantId: string) {
    return this.prisma.generatedDocument.findMany({
      where: { tenantId },
      orderBy: { createdAt: 'desc' },
      take: 50,
    })
  }

  async generate(tenantId: string, agentId: string | undefined, input: {
    type: string   // 'estimate' | 'inspection' | 'sow' | 'invoice' | 'custom'
    title: string
    data?: Record<string, any>
    prompt?: string  // if set, use AI to fill the template data
  }) {
    // Get company name
    const tenant = await this.prisma.tenant.findUnique({ where: { id: tenantId }, select: { name: true } })
    const company = tenant?.name ?? 'Your Company'

    let docData = input.data ?? {}

    // If a freeform prompt is provided, use AI to generate the document data
    if (input.prompt && (!input.data || Object.keys(input.data).length === 0)) {
      const systemPrompt = `You are a document generation assistant for ${company}. 
Generate structured JSON data for a ${input.type} document based on the user's request.
Respond ONLY with valid JSON matching the template fields for a ${input.type}.`
      try {
        const raw = await this.ai.chat(systemPrompt, [{ role: 'user', content: input.prompt }])
        const jsonMatch = raw.match(/\{[\s\S]*\}/)
        if (jsonMatch) docData = JSON.parse(jsonMatch[0])
      } catch (err: any) {
        this.logger.warn(`AI doc generation failed: ${err.message}`)
      }
    }

    // Render HTML
    const templateFn = TEMPLATES[input.type]
    const html = templateFn
      ? templateFn(docData, company)
      : wrapHTML(input.title, `<p>${JSON.stringify(docData, null, 2)}</p>`, company)

    // Convert HTML to PDF using puppeteer (if available), else save HTML
    let fileUrl: string
    let format = 'HTML'
    try {
      fileUrl = await this.renderPDF(html, input.title)
      format = 'PDF'
    } catch {
      // puppeteer not available — save HTML
      const filename = `${crypto.randomUUID()}.html`
      const filePath = path.join(this.outputDir, filename)
      fs.writeFileSync(filePath, html)
      fileUrl = `/generated-docs/${filename}`
    }

    return this.prisma.generatedDocument.create({
      data: {
        tenantId,
        agentId,
        title: input.title,
        type: input.type,
        format,
        fileUrl,
        content: docData as any,
        status: 'ready',
      },
    })
  }

  private async renderPDF(html: string, title: string): Promise<string> {
    const puppeteer = await import('puppeteer').then(m => m.default ?? m)
    const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] })
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'networkidle0' })
    const filename = `${crypto.randomUUID()}.pdf`
    const filePath = path.join(this.outputDir, filename)
    await page.pdf({ path: filePath, format: 'A4', printBackground: true, margin: { top: '15mm', bottom: '15mm', left: '15mm', right: '15mm' } })
    await browser.close()
    return `/generated-docs/${filename}`
  }

  async remove(tenantId: string, id: string) {
    const doc = await this.prisma.generatedDocument.findFirst({ where: { id, tenantId } })
    if (!doc) throw new NotFoundException('Document not found')
    if (doc.fileUrl) {
      const fp = path.join(process.cwd(), doc.fileUrl)
      if (fs.existsSync(fp)) fs.unlinkSync(fp)
    }
    return this.prisma.generatedDocument.delete({ where: { id } })
  }

  getTemplateTypes() {
    return [
      { id: 'estimate', label: 'Estimate / Proposal', description: 'Pricing estimate with line items for a job', fields: ['customerName', 'address', 'lineItems', 'notes'] },
      { id: 'inspection', label: 'Inspection Report', description: 'Detailed property inspection findings', fields: ['customerName', 'address', 'findings', 'recommendations'] },
      { id: 'sow', label: 'Statement of Work', description: 'Project scope, deliverables, and materials list', fields: ['projectTitle', 'customerName', 'deliverables', 'materials'] },
      { id: 'invoice', label: 'Invoice', description: 'Payment invoice for completed work', fields: ['customerName', 'lineItems', 'dueDate', 'total'] },
    ]
  }
}
