import { Injectable, NotFoundException, Logger } from '@nestjs/common'
import { PrismaService } from '../../common/prisma/prisma.service'
import { AIService } from '../../ai/ai.service'
import { DocumentTemplatesService } from '../document-templates/document-templates.service'
import { CloudinaryService } from '../../common/cloudinary/cloudinary.service'
import * as fs from 'fs'
import * as path from 'path'
import * as crypto from 'crypto'

// ── HTML Templates ────────────────────────────────────────────────

function wrapHTML(title: string, body: string, company = 'Your Company'): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e; background: #fff; font-size: 13px; line-height: 1.6; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
    .company-name { font-size: 22px; font-weight: 700; color: #2563eb; }
    .doc-title { font-size: 18px; font-weight: 600; color: #1e293b; margin-top: 4px; }
    .doc-meta { text-align: right; font-size: 11px; color: #64748b; }
    h2 { font-size: 14px; font-weight: 600; color: #2563eb; text-transform: uppercase; letter-spacing: 0.05em; margin: 24px 0 10px; border-left: 3px solid #2563eb; padding-left: 8px; }
    table { width: 100%; border-collapse: collapse; margin: 10px 0; }
    th { background: #2563eb; color: white; padding: 8px 12px; text-align: left; font-size: 11px; text-transform: uppercase; }
    td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
    tr:nth-child(even) td { background: #f8fafc; }
    .total-row td { font-weight: 700; background: #eff6ff; border-top: 2px solid #2563eb; }
    .badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 11px; font-weight: 600; }
    .badge-blue { background: #dbeafe; color: #1d4ed8; }
    .badge-green { background: #dcfce7; color: #15803d; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 12px 0; }
    .info-block { padding: 12px; background: #f8fafc; border-radius: 8px; }
    .info-label { font-size: 10px; text-transform: uppercase; color: #94a3b8; font-weight: 600; margin-bottom: 4px; }
    .info-value { font-size: 13px; color: #1e293b; }
    p { margin: 6px 0; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="company-name">${company}</div>
      <div class="doc-title">${title}</div>
    </div>
    <div class="doc-meta">
      <div>Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
      <div>Doc #: ${crypto.randomBytes(3).toString('hex').toUpperCase()}</div>
    </div>
  </div>
  ${body}
  <div class="footer">Generated by AI Workforce OS · ${company}</div>
</body>
</html>`
}

const asArray = (value: any) => Array.isArray(value) ? value : value ? [value] : []

const TEMPLATES: Record<string, (data: any, company: string) => string> = {
  estimate: (data, company) => wrapHTML('ESTIMATE / PROPOSAL', `
    <div class="info-grid">
      <div class="info-block"><div class="info-label">Customer</div><div class="info-value">${data.customerName ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Property Address</div><div class="info-value">${data.address ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Phone</div><div class="info-value">${data.phone ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Email</div><div class="info-value">${data.email ?? 'N/A'}</div></div>
    </div>
    <h2>Scope of Work</h2>
    <p>${data.scopeOfWork ?? 'To be determined during site inspection.'}</p>
    <h2>Line Items</h2>
    <table>
      <tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>
      ${(data.lineItems ?? []).map((li: any) => `<tr><td>${li.description}</td><td>${li.qty ?? 1}</td><td>$${Number(li.unitPrice ?? 0).toFixed(2)}</td><td>$${(Number(li.qty ?? 1) * Number(li.unitPrice ?? 0)).toFixed(2)}</td></tr>`).join('')}
      <tr class="total-row"><td colspan="3">TOTAL</td><td>$${(data.total ?? (data.lineItems ?? []).reduce((s: number, i: any) => s + (i.qty ?? 1) * (i.unitPrice ?? 0), 0)).toFixed(2)}</td></tr>
    </table>
    <h2>Notes</h2>
    <p>${data.notes ?? 'This estimate is valid for 30 days from the date above.'}</p>
  `, company),

  inspection: (data, company) => wrapHTML('INSPECTION REPORT', `
    <div class="info-grid">
      <div class="info-block"><div class="info-label">Property Address</div><div class="info-value">${data.address ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Customer</div><div class="info-value">${data.customerName ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Inspector</div><div class="info-value">${data.inspector ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Date Inspected</div><div class="info-value">${data.inspectionDate ?? new Date().toLocaleDateString()}</div></div>
    </div>
    <h2>Overall Condition</h2>
    <p><span class="badge badge-blue">${data.overallCondition ?? 'Requires Assessment'}</span></p>
    <p style="margin-top:8px">${data.summary ?? ''}</p>
    <h2>Findings</h2>
    <table>
      <tr><th>Area</th><th>Condition</th><th>Severity</th><th>Notes</th></tr>
      ${(data.findings ?? []).map((f: any) => `<tr><td>${f.area}</td><td>${f.condition}</td><td><span class="badge ${f.severity === 'High' ? 'badge-blue' : 'badge-green'}">${f.severity}</span></td><td>${f.notes ?? ''}</td></tr>`).join('')}
    </table>
    <h2>Recommended Actions</h2>
    <p>${data.recommendations ?? 'Full replacement recommended within 6 months.'}</p>
    <h2>Photos / Evidence</h2>
    <p>${data.photos ?? 'Photos taken and available upon request.'}</p>
  `, company),

  sow: (data, company) => wrapHTML('STATEMENT OF WORK', `
    <div class="info-grid">
      <div class="info-block"><div class="info-label">Project</div><div class="info-value">${data.projectTitle ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Customer</div><div class="info-value">${data.customerName ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Start Date</div><div class="info-value">${data.startDate ?? 'TBD'}</div></div>
      <div class="info-block"><div class="info-label">Completion</div><div class="info-value">${data.endDate ?? 'TBD'}</div></div>
    </div>
    <h2>Project Overview</h2>
    <p>${data.overview ?? ''}</p>
    <h2>Deliverables</h2>
    ${(data.deliverables ?? []).map((d: string) => `<p>• ${d}</p>`).join('')}
    <h2>Materials</h2>
    <table>
      <tr><th>Material</th><th>Quantity</th><th>Supplier</th></tr>
      ${(data.materials ?? []).map((m: any) => `<tr><td>${m.name}</td><td>${m.quantity} ${m.unit ?? ''}</td><td>${m.supplier ?? 'TBD'}</td></tr>`).join('')}
    </table>
    <h2>Terms & Conditions</h2>
    <p>${data.terms ?? 'Payment due upon project completion. Warranty: 1 year on workmanship.'}</p>
  `, company),

  invoice: (data, company) => wrapHTML('INVOICE', `
    <div class="info-grid">
      <div class="info-block"><div class="info-label">Bill To</div><div class="info-value">${data.customerName ?? 'N/A'}<br>${data.address ?? ''}</div></div>
      <div class="info-block"><div class="info-label">Invoice Details</div><div class="info-value">Due: ${data.dueDate ?? '30 days'}<br>Status: <span class="badge badge-blue">${data.status ?? 'Unpaid'}</span></div></div>
    </div>
    <h2>Services Rendered</h2>
    <table>
      <tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>
      ${(data.lineItems ?? []).map((li: any) => `<tr><td>${li.description}</td><td>${li.qty ?? 1}</td><td>$${Number(li.rate ?? li.unitPrice ?? 0).toFixed(2)}</td><td>$${(Number(li.qty ?? 1) * Number(li.rate ?? li.unitPrice ?? 0)).toFixed(2)}</td></tr>`).join('')}
      <tr class="total-row"><td colspan="3">TOTAL DUE</td><td>$${(data.total ?? 0).toFixed(2)}</td></tr>
    </table>
    <h2>Payment Instructions</h2>
    <p>${data.paymentInstructions ?? 'Please make payment via bank transfer or check. Include invoice number as reference.'}</p>
  `, company),

  supplement: (data, company) => wrapHTML('SUPPLEMENT REQUEST', `
    <div class="info-grid">
      <div class="info-block"><div class="info-label">Prepared By</div><div class="info-value">${data.preparedBy ?? company}</div></div>
      <div class="info-block"><div class="info-label">Carrier</div><div class="info-value">${data.carrier ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Policy Number</div><div class="info-value">${data.policyNumber ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Claim Number</div><div class="info-value">${data.claimNumber ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Insured / Customer</div><div class="info-value">${data.customerName ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Property Address</div><div class="info-value">${data.propertyAddress ?? data.address ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Date of Loss</div><div class="info-value">${data.dateOfLoss ?? 'N/A'}</div></div>
      <div class="info-block"><div class="info-label">Cause of Loss</div><div class="info-value">${data.causeOfLoss ?? 'N/A'}</div></div>
    </div>

    <h2>1. Claim Summary</h2>
    <p>${data.claimSummary ?? 'Claim summary not provided.'}</p>

    <h2>2. Approved Scope</h2>
    <table>
      <tr><th>Approved Item</th><th>Amount</th></tr>
      ${asArray(data.approvedScope).map((item: any) => `<tr><td>${item.description ?? item.item ?? item}</td><td>${item.amount ? `$${Number(item.amount).toFixed(2)}` : 'N/A'}</td></tr>`).join('')}
    </table>

    <h2>3. Missing Items</h2>
    ${asArray(data.missingItems).map((item: any) => `<p>• ${item.description ?? item.item ?? item}${item.reason ? ` — ${item.reason}` : ''}</p>`).join('') || '<p>No missing items listed.</p>'}

    <h2>4. Underpaid Items</h2>
    <table>
      <tr><th>Item</th><th>Approved</th><th>Recommended</th><th>Reason</th></tr>
      ${asArray(data.underpaidItems).map((item: any) => `<tr><td>${item.description ?? item.item ?? ''}</td><td>${item.approvedAmount ? `$${Number(item.approvedAmount).toFixed(2)}` : 'N/A'}</td><td>${item.recommendedAmount ? `$${Number(item.recommendedAmount).toFixed(2)}` : 'N/A'}</td><td>${item.reason ?? ''}</td></tr>`).join('')}
    </table>

    <h2>5. Documentation Needed</h2>
    ${asArray(data.documentationNeeded).map((item: string) => `<p>• ${item}</p>`).join('') || '<p>No additional documentation listed.</p>'}

    <h2>6. Recommended Additional Line Items</h2>
    <table>
      <tr><th>Line Item</th><th>Estimated Value</th><th>Justification</th></tr>
      ${asArray(data.recommendedLineItems).map((item: any) => `<tr><td>${item.description ?? item.item ?? ''}</td><td>${item.estimatedValue ? `$${Number(item.estimatedValue).toFixed(2)}` : 'N/A'}</td><td>${item.justification ?? ''}</td></tr>`).join('')}
      <tr class="total-row"><td>Total Estimated Supplement</td><td colspan="2">$${Number(data.supplementTotal ?? 0).toFixed(2)}</td></tr>
    </table>

    <h2>7. Contractor Notes / Action Plan</h2>
    ${asArray(data.actionPlan ?? data.contractorNotes).map((item: string, idx: number) => `<p>${idx + 1}. ${item}</p>`).join('') || '<p>No action plan provided.</p>'}

    <h2>Supplement Summary</h2>
    <p><strong>Estimated Supplement Value:</strong> $${Number(data.supplementTotal ?? 0).toFixed(2)}</p>
    <p><strong>Confidence Level:</strong> ${data.confidenceLevel ?? 'Medium'}</p>
  `, company),
}

@Injectable()
export class DocumentsService {
  private readonly logger = new Logger(DocumentsService.name)
  private readonly outputDir = process.env.GENERATED_DOCS_DIR || path.join(process.cwd(), 'generated-docs')

  constructor(
    private readonly prisma: PrismaService,
    private readonly ai: AIService,
    private readonly docTemplates: DocumentTemplatesService,
    private readonly cloudinary: CloudinaryService,
  ) {
    if (!fs.existsSync(this.outputDir)) fs.mkdirSync(this.outputDir, { recursive: true })
  }

  findAll(tenantId: string) {
    return this.prisma.generatedDocument.findMany({
      where: { tenantId },
      orderBy: { createdAt: 'desc' },
      take: 50,
    })
  }

  async generate(tenantId: string, agentId: string | undefined, input: {
    type: string   // 'estimate' | 'inspection' | 'sow' | 'invoice' | 'supplement' | 'custom'
    title: string
    data?: Record<string, any>
    prompt?: string  // if set, use AI to fill the template data
  }) {
    // Get company name
    const tenant = await this.prisma.tenant.findUnique({ where: { id: tenantId }, select: { name: true } })
    const company = tenant?.name ?? 'Your Company'

    let docData = input.data ?? {}

    // If a freeform prompt is provided, use AI to generate the document data
    if (input.prompt && (!input.data || Object.keys(input.data).length === 0)) {
      const SCHEMA_HINTS: Record<string, string> = {
        estimate: `{
  "customerName": "string",
  "address": "string",
  "phone": "string (optional)",
  "email": "string (optional)",
  "scopeOfWork": "string describing the work",
  "lineItems": [{ "description": "string", "qty": number, "unitPrice": number }],
  "notes": "string (optional, e.g. validity period)",
  "total": number (sum of all line items)
}`,
        inspection: `{
  "customerName": "string",
  "address": "string",
  "inspector": "string",
  "inspectionDate": "string (date)",
  "overallCondition": "string e.g. Good / Fair / Poor",
  "summary": "string",
  "findings": [{ "area": "string", "condition": "string", "severity": "High|Low", "notes": "string" }],
  "recommendations": "string",
  "photos": "string (optional)"
}`,
        sow: `{
  "projectTitle": "string",
  "customerName": "string",
  "startDate": "string",
  "endDate": "string",
  "overview": "string",
  "deliverables": ["string", "string"],
  "materials": [{ "name": "string", "quantity": number, "unit": "string", "supplier": "string (optional)" }],
  "terms": "string (optional)"
}`,
        invoice: `{
  "customerName": "string",
  "address": "string",
  "dueDate": "string e.g. 30 days",
  "status": "Unpaid|Paid",
  "lineItems": [{ "description": "string", "qty": number, "rate": number }],
  "total": number,
  "paymentInstructions": "string (optional)"
}`,
        supplement: `{
  "preparedBy": "string",
  "customerName": "string",
  "propertyAddress": "string",
  "carrier": "string",
  "policyNumber": "string",
  "claimNumber": "string",
  "dateOfLoss": "string",
  "causeOfLoss": "string",
  "adjuster": "string",
  "claimStatus": "string",
  "claimSummary": "string",
  "approvedScope": [{ "description": "string", "amount": number }],
  "missingItems": [{ "description": "string", "reason": "string" }],
  "underpaidItems": [{ "description": "string", "approvedAmount": number, "recommendedAmount": number, "reason": "string" }],
  "documentationNeeded": ["string"],
  "recommendedLineItems": [{ "description": "string", "estimatedValue": number, "justification": "string" }],
  "actionPlan": ["string"],
  "supplementTotal": number,
  "confidenceLevel": "High|Medium|Low"
}`,
      }

      const schemaHint = SCHEMA_HINTS[input.type] ?? '{}'
      const systemPrompt = `You are a document data extraction assistant for ${company}.
Extract structured data from the user's request and return ONLY valid JSON matching this exact schema:
${schemaHint}

Rules:
- Use ONLY the field names shown above — do not add or rename fields
- Calculate "total" as the sum of all line items (qty * unitPrice or qty * rate)
- For supplement documents, calculate "supplementTotal" as the sum of recommendedLineItems estimatedValue plus any underpaid deltas when applicable
- If a value is not mentioned, use a sensible default or empty string
- Respond with ONLY the JSON object, no explanation, no markdown`

      try {
        const raw = await this.ai.chat(systemPrompt, [{ role: 'user', content: input.prompt }])
        const jsonMatch = raw.match(/\{[\s\S]*\}/)
        if (jsonMatch) docData = JSON.parse(jsonMatch[0])
        this.logger.log(`AI doc data generated for type=${input.type}: ${JSON.stringify(docData).slice(0, 200)}`)
      } catch (err: any) {
        this.logger.warn(`AI doc generation failed: ${err.message}`)
      }
    }

    // Resolve template: 1) tenant's saved default → 2) auto-generate & save → 3) built-in fallback
    let html: string
    let resolvedTemplate = await this.docTemplates.findDefault(tenantId, input.type)

    if (!resolvedTemplate && TEMPLATES[input.type] && input.type !== 'supplement') {
      // Auto-generate a professional template the first time this doc type is used
      try {
        const tenantFull = await this.prisma.tenant.findUnique({
          where: { id: tenantId },
          select: { industry: true, settings: true },
        })
        const industry = (tenantFull?.industry ?? 'general').toLowerCase().replace(/_/g, ' ')
        const brandColor = (tenantFull?.settings as any)?.brain?.primaryColor ?? '#2563eb'

        this.logger.log(`Auto-generating professional template for type=${input.type} industry=${industry}`)
        const generated = await this.docTemplates.generateProfessionalTemplate(
          input.type,
          industry,
          'modern',
          brandColor,
          'formal',
          'print',
        )

        resolvedTemplate = await this.docTemplates.create(tenantId, {
          name: generated.suggestedName,
          type: input.type,
          description: `Auto-generated ${input.type} template for ${company}`,
          htmlBody: generated.htmlBody,
          isDefault: true,
        })
        this.logger.log(`Saved new professional template "${resolvedTemplate.name}" (id=${resolvedTemplate.id})`)
      } catch (err: any) {
        this.logger.warn(`Professional template auto-generation failed: ${err.message} — using built-in fallback`)
      }
    }

    if (resolvedTemplate) {
      this.logger.log(`Using template "${resolvedTemplate.name}" for type=${input.type}`)
      html = this.docTemplates.renderTemplate(resolvedTemplate.htmlBody, { ...docData, companyName: company })
    } else {
      const templateFn = TEMPLATES[input.type]
      html = templateFn
        ? templateFn(docData, company)
        : wrapHTML(input.title, `<p>${JSON.stringify(docData, null, 2)}</p>`, company)
    }

    // Convert HTML to PDF using puppeteer (if available), else save HTML
    let fileUrl: string
    let format = 'HTML'
    try {
      fileUrl = await this.renderPDF(html, input.title, tenantId)
      format = 'PDF'
    } catch {
      // puppeteer not available — save as HTML
      const filename = `${crypto.randomUUID()}.html`
      const buffer = Buffer.from(html, 'utf8')
      fileUrl = await this.cloudinary.upload(tenantId, 'generated-docs', filename, buffer, 'text/html', 'raw')
    }

    return this.prisma.generatedDocument.create({
      data: {
        tenantId,
        agentId,
        title: input.title,
        type: input.type,
        format,
        fileUrl,
        content: docData as any,
        status: 'ready',
      },
    })
  }

  private async renderPDF(html: string, title: string, tenantId: string): Promise<string> {
    const puppeteer = await import('puppeteer').then(m => m.default ?? m)
    const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] })
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'networkidle0' })
    const filename = `${crypto.randomUUID()}.pdf`
    const tmpPath = path.join(this.outputDir, filename)
    await page.pdf({ path: tmpPath, format: 'A4', printBackground: true, margin: { top: '15mm', bottom: '15mm', left: '15mm', right: '15mm' } })
    await browser.close()

    // Upload generated PDF to Cloudinary then clean up the temp file
    const buffer = fs.readFileSync(tmpPath)
    const fileUrl = await this.cloudinary.upload(tenantId, 'generated-docs', filename, buffer, 'application/pdf', 'raw')
    fs.unlinkSync(tmpPath)
    return fileUrl
  }

  async remove(tenantId: string, id: string) {
    const doc = await this.prisma.generatedDocument.findFirst({ where: { id, tenantId } })
    if (!doc) throw new NotFoundException('Document not found')
    if (doc.fileUrl) await this.cloudinary.delete(doc.fileUrl)
    return this.prisma.generatedDocument.delete({ where: { id } })
  }

  resolveStoredFile(fileUrl: string) {
    // Legacy local path support
    if (fileUrl.startsWith('/')) {
      const filename = path.basename(fileUrl)
      return path.join(this.outputDir, filename)
    }
    return fileUrl
  }

  getTemplateTypes() {
    return [
      { id: 'estimate', label: 'Estimate / Proposal', description: 'Pricing estimate with line items for a job', fields: ['customerName', 'address', 'lineItems', 'notes'] },
      { id: 'inspection', label: 'Inspection Report', description: 'Detailed property inspection findings', fields: ['customerName', 'address', 'findings', 'recommendations'] },
      { id: 'sow', label: 'Statement of Work', description: 'Project scope, deliverables, and materials list', fields: ['projectTitle', 'customerName', 'deliverables', 'materials'] },
      { id: 'invoice', label: 'Invoice', description: 'Payment invoice for completed work', fields: ['customerName', 'lineItems', 'dueDate', 'total'] },
    ]
  }
}
