/**
 * Seeds / syncs team members from hierarchy-export.json onto the server DB.
 *
 * - Matches existing users by email → updates profile fields
 * - Creates missing users with a temporary hashed password (they must reset via forgot-password)
 * - Links managers by email
 * - Safe to re-run (all upserts, no duplicates)
 *
 * Usage: node scripts/seed-team.js
 * Requires: scripts/hierarchy-export.json (generated by export-hierarchy.js)
 */

const { PrismaClient } = require('../apps/api/node_modules/@prisma/client')
const bcrypt = require('../apps/api/node_modules/bcryptjs')
const fs = require('fs')
const path = require('path')

const p = new PrismaClient()

// Temporary password for newly created users — they should reset via forgot-password
const TEMP_PASSWORD = 'Welcome@2024!'

async function main() {
  const exportPath = path.join(__dirname, 'hierarchy-export.json')
  if (!fs.existsSync(exportPath)) {
    console.log('❌ hierarchy-export.json not found. Run export-hierarchy.js locally first.')
    process.exit(1)
  }

  const data = JSON.parse(fs.readFileSync(exportPath, 'utf-8'))
  console.log(`\n📥 Seeding team from export dated: ${data.exportedAt}`)

  // Filter only the Xtreme Cleaning tenant users (skip platform admin / QA users)
  const teamUsers = data.users.filter(u =>
    u.email &&
    !u.email.includes('superadmin@') &&
    !u.email.includes('qa') &&
    !u.name?.toLowerCase().includes('qa') &&
    !u.name?.toLowerCase().includes('platform admin') &&
    !u.name?.toLowerCase().includes('super admin'),
  )

  console.log(`\n📋 Team members to seed: ${teamUsers.length}`)
  for (const u of teamUsers) {
    console.log(`   - ${u.name} <${u.email}> | ${u.designation || u.role}`)
  }

  // ── Step 1: Find or create each user ───────────────────────────
  const hashedTemp = await bcrypt.hash(TEMP_PASSWORD, 10)
  const emailToServerId = new Map()

  // ── Pre-build local tenantId → server tenantId map ─────────────
  // For each unique local tenantId, find a matching server tenant by
  // looking up any user from that tenant that already exists on the server.
  console.log('\n🔍 Resolving tenant mappings...')
  const localTenantToServer = new Map() // localTenantId → { id, name }

  const uniqueLocalTenantIds = [...new Set(teamUsers.map(u => u.tenantId))]
  for (const localTenantId of uniqueLocalTenantIds) {
    const usersInTenant = teamUsers.filter(u => u.tenantId === localTenantId)

    // Try by tenant name first
    const exportedTenant = data.hierarchies.find(h => h.tenantId === localTenantId)
    if (exportedTenant?.tenantName) {
      const byName = await p.tenant.findFirst({
        where: { name: { equals: exportedTenant.tenantName, mode: 'insensitive' } },
        select: { id: true, name: true },
      })
      if (byName) { localTenantToServer.set(localTenantId, byName); continue }
    }

    // Fallback: find any user from this tenant that already exists on server
    for (const u of usersInTenant) {
      const existing = await p.user.findFirst({
        where: { email: u.email },
        select: { id: true, tenantId: true },
      })
      if (existing) {
        const tenant = await p.tenant.findUnique({
          where: { id: existing.tenantId },
          select: { id: true, name: true },
        })
        if (tenant) { localTenantToServer.set(localTenantId, tenant); break }
      }
    }

    if (!localTenantToServer.has(localTenantId)) {
      console.log(`   ⚠️  Could not resolve tenant for localId ...${localTenantId.slice(-6)}`)
    } else {
      console.log(`   ✅ Tenant mapped: ...${localTenantId.slice(-6)} → "${localTenantToServer.get(localTenantId).name}"`)
    }
  }

  console.log('\n👥 Creating / updating users...')

  for (const u of teamUsers) {
    const serverTenant = localTenantToServer.get(u.tenantId)

    if (!serverTenant) {
      console.log(`   ⚠️  Tenant not found for ${u.email} — skipping`)
      continue
    }

    // Upsert user
    const existing = await p.user.findFirst({
      where: { email: u.email, tenantId: serverTenant.id },
      select: { id: true },
    })

    let serverId

    if (existing) {
      await p.user.update({
        where: { id: existing.id },
        data: {
          name: u.name,
          designation: u.designation ?? undefined,
          department: u.department || undefined,
          phone: u.phone || undefined,
          role: u.role,
          isActive: true,
        },
      })
      serverId = existing.id
      console.log(`   ✅ Updated:  ${u.name} <${u.email}>`)
    } else {
      // Create new user with temp password
      const created = await p.user.create({
        data: {
          email: u.email,
          name: u.name,
          password: hashedTemp,
          role: u.role,
          designation: u.designation ?? undefined,
          department: u.department || undefined,
          phone: u.phone || undefined,
          tenantId: serverTenant.id,
          isActive: true,
        },
      })
      serverId = created.id
      console.log(`   🆕 Created:  ${u.name} <${u.email}> (temp password: ${TEMP_PASSWORD})`)
    }

    emailToServerId.set(u.email.toLowerCase(), serverId)
  }

  // ── Step 2: Link managers now that all users exist ──────────────
  console.log('\n🔗 Linking manager relationships...')

  for (const u of teamUsers) {
    if (!u._managerEmail) continue

    const serverId = emailToServerId.get(u.email.toLowerCase())
    const managerServerId = emailToServerId.get(u._managerEmail.toLowerCase())

    if (!serverId || !managerServerId) continue

    await p.user.update({
      where: { id: serverId },
      data: { managerId: managerServerId },
    })
    console.log(`   ✅ ${u.name} → reports to → ${u._managerEmail}`)
  }

  // ── Step 3: Summary ─────────────────────────────────────────────
  console.log('\n📊 Final team on server:')
  const allServerUsers = await p.user.findMany({
    where: { email: { in: teamUsers.map(u => u.email) } },
    select: { name: true, email: true, designation: true, phone: true, managerId: true },
    orderBy: { name: 'asc' },
  })
  for (const u of allServerUsers) {
    console.log(`   ${u.name} | ${u.designation || '-'} | phone: ${u.phone || 'none'} | manager: ${u.managerId ? '✅' : '—'}`)
  }

  console.log(`\n🎉 Team seed complete!`)
  console.log(`   Next: run  node scripts/import-hierarchy.js  to sync the org chart layout.`)
  console.log(`   Users created with temp password: ${TEMP_PASSWORD}`)
  console.log(`   Ask them to reset via Forgot Password on the login page.`)
}

main().then(() => p.$disconnect()).catch(e => { console.error(e); p.$disconnect() })
